In [5]:
#jawaban soal 1
nama = "Shefia Anggraeni"
kode_matakuliah = "CIE407"
mata_kuliah = "Machine Learning"

print("DATA DIRI")
print("Nama : ", nama)
print("Kode Dosen: ", kode_matakuliah)
print("Perkuliahan: ", mata_kuliah)

DATA DIRI
Nama :  Shefia Anggraeni
Kode Dosen:  CIE407
Perkuliahan:  Machine Learning


In [6]:
#jawaban soal2
matriksC= [[1,2,3],[4,5,6]]
print(matriksC)

[[1, 2, 3], [4, 5, 6]]


In [7]:
#jawaban soal 3
matriks = [[2,2],[2,2],[2,2]]
print(matriks)

[[2, 2], [2, 2], [2, 2]]


In [14]:
#jawaban 4
import numpy as np

#jawaban 5
from numpy import *
matriks = range(32)
matriks = reshape(matriks, (4,8))
print(matriks)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [16]:
#jawaban 6
import numpy as np
from numpy import *

matriks = np.random.randint(1,5,(3,30))
print(matriks)

[[4 1 3 3 4 1 1 4 1 4 1 2 3 4 4 4 3 1 2 2 2 1 2 3 4 1 2 1 3 2]
 [4 1 2 2 3 1 2 3 3 3 3 4 1 3 4 1 3 3 2 1 1 4 1 1 2 4 2 4 4 2]
 [1 4 2 4 4 2 2 1 2 4 2 1 2 1 4 4 2 4 1 1 3 4 1 2 2 1 3 1 4 3]]
